[package]
name = "clock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
crossterm = "0.27.0"
ctrlc = "3.4.4"
lazy_static = "1.4.0"
ndarray = "0.15.6"
